# Display aktivieren
CONFIG_ZMK_DISPLAY=y
CONFIG_ZMK_DISPLAY_STATUS_SCREEN_CUSTOM=y

# WPM (Wörter pro Minute) aktivieren
CONFIG_ZMK_WPM=y

# nice-oled Widgets
CONFIG_NICE_OLED_WIDGET_WPM=y
CONFIG_NICE_OLED_WIDGET_BATTERY=y
CONFIG_NICE_OLED_WIDGET_LAYER_STATUS=y

# Batterie-Anzeige
CONFIG_ZMK_BATTERY_REPORTING=y
