manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: joelspadin
      url-base: https://github.com/joelspadin
    - name: mctechnology17
      url-base: https://github.com/mctechnology17
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    # Deutsches Layout (DE_* Keycodes)
    - name: zmk-locales
      remote: joelspadin
      revision: main
    # nice!view Custom Widgets (WPM, Batterie, Logos)
    - name: zmk-nice-oled
      remote: mctechnology17
      revision: main
  self:
    path: config
